name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php:
          - 8.1
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - run: make
      - run: docker compose build
      - run: docker compose up -d
      - run: bash tests/await.bash http://clue.localhost/
      - run: make test
      - run: docker compose stop -t 60
        timeout-minutes: 0.5
      - run: docker compose logs
        if: ${{ always() }}
      - run: git config --global user.name "GitHub Actions" && git config --global user.email "actions@github.com"
      - run: git config --global url."https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - run: make deploy
        if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
