name: CI

on:
  push:
  pull_request:

jobs:
  Acceptance:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php:
          - 8.1
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - run: composer install
      - run: vendor/bin/sculpin generate
      - run: docker run -d -p 8080:80 -v "$PWD"/build:/var/www/html php:7.4-apache sh -c "ln -s /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled; apache2-foreground"
      - run: tests/acceptance.sh http://localhost:8080
