name: CI

on:
  push:
  pull_request:

jobs:
  Acceptance:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php:
          - 8.1
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - run: make
      - run: make served
      - run: make test
