name: Diff HTML pages

# Triggers the workflow only for pull requests
on:
  pull_request:

jobs:
  diff:
    runs-on: ubuntu-latest

    steps:
      # check out base ref and build site into old/
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          ref: ${{ github.event.pull_request.base.sha }}
      - run: composer install
      - run: vendor/bin/sculpin generate --output-dir=old

      # check out head ref and build site into new/
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          clean: false # Prevent removing files in old/
      - run: composer install
      - run: vendor/bin/sculpin generate --output-dir=new

      # Diff between old and new
      - name: Diff between old and new
        run: |
          git diff --no-index --stat --color=always old new && echo No changed detected || true
          diff -r -u --color=always old new || true
